name: Node.js Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: pwd
    - run: ls -ltr
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: drop
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/
          
